---
fixtures:
  repositories:
    augeasproviders_core:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_core
    augeasproviders_sysctl:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_sysctl
    simplib:
      repo: https://github.com/simp/pupmod-simp-simplib
      branch: 5.X
    stdlib:
      branch: 5.X
      repo: https://github.com/simp/puppetlabs-stdlib
    sysctl:
      repo: https://github.com/simp/pupmod-simp-sysctl
      branch: 5.X
  symlinks:
    libvirt: "#{source_dir}"
